---

- hosts: all

  tasks:

  - name: add Ubuntu security main repository
    template: src=templates/etc_apt_sources.list.d_ubuntu-security-main.list.j2 dest=/etc/apt/sources.list.d/ubuntu-security-main.list owner=root group=root mode=0644
    when: ansible_distribution == 'Ubuntu'

- include: ../apt/update.yml

