---

- hosts: all

  tasks:
  - name: add Ubuntu universe repository
    template: src=templates/etc_apt_sources.list.d_ubuntu-universe.list.j2 dest=/etc/apt/sources.list.d/ubuntu-universe.list

- include: apt_cache_update.yml

