---

- include: ../apt/setup.yml
- include: add_repo_universe.yml

- hosts: all

  tasks:

  - name: install more packages
    apt: name=$item
    with_items:
    - bash-completion
    - command-not-found
    - language-pack-en-base
    - mc
    - strace
    - tcpdump
    - telnet
    - traceroute

