---

- hosts: all

  vars:
  - tmpdir: /tmp

  tasks:

  - name: check current date
    command: date +%Y%m%d-%H%M%S
    register: date

  - name: backup foswiki
    command: tar --create --directory /var/www/foswiki --gzip --file $tmpdir/foswiki-backup-${date.stdout}.tgz .

  - name: fetch backup
    fetch: src=$tmpdir/foswiki-backup-${date.stdout}.tgz dest=../../backups

  - name: remove backup from server
    command: rm -f $tmpdir/foswiki-backup-${date.stdout}.tgz

