---
  - include: tasks/mysql.yml

  - name: install phpmyadmin
    apt: pkg=phpmyadmin

  - name: configure apache2
    file: src=/etc/phpmyadmin/apache.conf dest=/etc/apache2/conf.d/phpmyadmin.conf state=link
    notify: restart apache2
