---

- include: prepare.yml

- include: ../ubuntu/add_repo_universe.yml

- include: ../apache2/setup.yml

- hosts: all

  tasks:
  - name: install phpmyadmin
    apt: pkg=phpmyadmin

  - name: configure apache2
    file: src=/etc/phpmyadmin/apache.conf dest=/etc/apache2/conf.d/phpmyadmin.conf state=link

- include: ../apache2/restart.yml

