---

- hosts: all

  tasks:

  - name: install ssh authorized keys for ansible (directory)
    file: path=/root/.ssh owner=root group=root mode=0700 state=directory

  - name: install ssh authorized keys for ansible (file)
    copy: src=../../keys/id_rsa.pub dest=/root/.ssh/authorized_keys_ansible owner=root group=root mode=0600

  - name: append key for ansible to authorized keys file
    shell: test $(cat /root/.ssh/authorized_keys | sort -u | wc -l) = $(cat /root/.ssh/authorized_keys /root/.ssh/authorized_keys_ansible | sort -u | wc -l) || { cat /root/.ssh/authorized_keys_ansible >> /root/.ssh/authorized_keys; chmod 0600 /root/.ssh/authorized_keys; }

