---

- hosts: all

  tasks:

  - name: install ssh server private keys
    copy: src=../../keys/ssh_host_${item}_key dest=/etc/ssh/ssh_host_${item}_key mode=0600
    with_items:
    - dsa
    - ecdsa
    - rsa

  - name: install ssh server public keys
    copy: src=../../keys/ssh_host_${item}_key.pub dest=/etc/ssh/ssh_host_${item}_key.pub mode=0644
    with_items:
    - dsa
    - ecdsa
    - rsa

  - name: install ssh server public keys ascii-art fingerprint
    copy: src=../../keys/ssh_host_${item}_key.asc dest=/etc/ssh/ssh_host_${item}_key.asc mode=0644
    with_items:
    - dsa
    - ecdsa
    - rsa

  - name: install ssh authorized keys for ansible (directory)
    file: path=/root/.ssh mode=0700 state=directory

  - name: install ssh authorized keys for ansible (file)
    copy: src=../../keys/id_rsa.pub dest=/root/.ssh/authorized_keys_ansible mode=0600

  - name: append key for ansible to authorized keys file
    shell: test $(cat /root/.ssh/authorized_keys | sort -u | wc -l) = $(cat /root/.ssh/authorized_keys /root/.ssh/authorized_keys_ansible | sort -u | wc -l) || { cat /root/.ssh/authorized_keys_ansible >> /root/.ssh/authorized_keys; chmod 0600 /root/.ssh/authorized_keys; }

  - name: restart ssh
    service: name=ssh state=restarted

