---

- hosts: all

  vars:
    vendor: Debian
    suite: stable
    mirror: http://ftp.debian.org/debian/
    nameserver: '8.8.8.8 8.8.4.4'
    hostname: ~
    dnsdomainname: ~
    ssh_port: 2220

  tasks:

  - name: enable networking (/etc/network/interfaces)
    copy: src=files/etc_network_interfaces dest=/etc/network/interfaces

  - name: enable networking (/etc/hosts)
    copy: src=files/etc_hosts dest=/etc/hosts

  - name: enable networking (/etc/resolv.conf)
    template: src=templates/etc_resolv.conf.j2 dest=/etc/resolvconf/resolv.conf.d/base

  - name: enable networking (clean resolvconf at /etc)
    file: path=/etc/resolvconf/resolv.conf.d/original state=absent

  - name: enable networking (clean resolvconf at /run)
    file: path=/run/resolvconf/interface/original.resolvconf state=absent

  - name: clean up /etc/hostname
    file: path=/etc/hostname state=absent

  - name: set /etc/hostname
    template: src=templates/etc_hostname.j2 dest=/etc/hostname
    when_set: $hostname

  - name: set /etc/dnsdomainname
    template: src=templates/etc_dnsdomainname.j2 dest=/etc/dnsdomainname
    when_set: $dnsdomainname

  - name: configure apt
    template: src=templates/etc_apt_sources.list.j2 dest=/etc/apt/sources.list

  - name: divert initctl
    command: dpkg-divert --rename /sbin/initctl

  - name: install wrapper for initctl
    copy: src=files/sbin_initctl dest=/sbin/initctl mode=0755

  - name: divert upstart-job
    command: dpkg-divert --divert /lib/init/upstart-job.sh --rename /lib/init/upstart-job

  - name: install wrapper for upstart-job
    copy: src=files/lib_init_upstart-job dest=/lib/init/upstart-job mode=0755

  - name: clean all init.d scripts for level 0 (setup-stop) and 2 (setup-start)
    shell: rm -f /etc/rc[02].d/[SK][0-9][0-9]$item
    with_items:
    - halt
    - ondemand
    - sendsigs
    - umountfs
    - umountnfs.sh
    - umountroot
    - urandom

  - name: init.d rc.local (remove)
    command: update-rc.d -f rc.local remove

  - name: init.d rc.local (add)
    command: update-rc.d rc.local start 99 2 3 4 5 .

  - name: init.d dnsdomainname.sh (install)
    copy: src=files/etc_init.d_dnsdomainname.sh dest=/etc/init.d/dnsdomainname.sh mode=0755

  - name: init.d dnsdomainname.sh (tweak)
    command: sed -i 's/^\(# Default-Start:\).*$/\\1     S 2/' /etc/init.d/dnsdomainname.sh

  - name: init.d dnsdomainname.sh (remove)
    command: update-rc.d -f dnsdomainname.sh remove

  - name: init.d dnsdomainname.sh (add)
    command: update-rc.d dnsdomainname.sh start 02 S 2 .

  - name: init.d sudo (remove)
    command: update-rc.d -f sudo remove

  - name: init.d sudo (add)
    command: update-rc.d sudo start 75 2 3 4 5 .

  - name: init.d rsyslog (install)
    copy: src=files/etc_init.d_rsyslog dest=/etc/init.d/rsyslog.sysv mode=0755

  - name: init.d rsyslog (remove)
    command: update-rc.d -f rsyslog remove

  - name: init.d rsyslog (add)
    command: update-rc.d rsyslog start 10 2 3 4 5 . start 30 0 6 . stop 90 1 .

  - name: init.d cron (install)
    copy: src=files/etc_init.d_cron dest=/etc/init.d/cron.sysv mode=0755

  - name: init.d cron (remove)
    command: update-rc.d -f cron remove

  - name: init.d cron (add)
    command: update-rc.d cron start 89 2 3 4 5 .

  - name: init.d resolvconf (install)
    copy: src=files/etc_init.d_resolvconf dest=/etc/init.d/resolvconf.sysv mode=0755

  - name: init.d resolvconf (tweak)
    command: sed -i 's/^\(# Default-Start:\).*$/\\1     S 2/' /etc/init.d/resolvconf.sysv

  - name: init.d resolvconf (remove)
    command: update-rc.d -f resolvconf remove

  - name: init.d resolvconf (add)
    command: update-rc.d resolvconf start 38 S 2 . stop 89 0 6 .

  - name: init_is_upstart
    command: ln -sf /bin/false /bin/init_is_upstart

  - name: init.d networking (install)
    copy: src=files/etc_init.d_networking dest=/etc/init.d/networking.sysv mode=0755

  - name: init.d networking (tweak)
    command: sed -i 's/^\(# Default-Start:\).*$/\\1     S 2/' /etc/init.d/networking.sysv

  - name: init.d networking (remove)
    command: update-rc.d -f networking remove

  - name: init.d networking (add)
    command: update-rc.d networking start 40 S 2 . start 35 0 6 .

  - name: init.d ssh (tweak)
    command: sed -i 's/^\(# Default-Stop:\).*$/\\1\t\t0 6/' /etc/init.d/ssh

  - name: init.d ssh (remove)
    command: update-rc.d -f ssh remove

  - name: init.d ssh (add)
    command: update-rc.d ssh start 16 2 3 4 5 . stop 90 0 6 .

  - name: init.d rc.chroot (install)
    copy: src=files/etc_init.d_rc.chroot dest=/etc/init.d/rc.chroot mode=0755

  - name: configure ssh server (SSHD_OPTS)
    command: sed -i "s/^\(SSHD_OPTS\)=.*/\\1='-p$ssh_port'/" /etc/default/ssh

  - name: configure ssh server (Port)
    command: sed -i "s,^#*[[:space:]]*\(Port\).*,\\1 $ssh_port," /etc/ssh/sshd_config

  - name: configure ssh server (AuthorizedKeysFile)
    command: sed -i "s,^#*[[:space:]]*\(AuthorizedKeysFile\).*,\\1 %h/.ssh/authorized_keys %h/.ssh/authorized_keys_ansible," /etc/ssh/sshd_config

  - name: configure syslog
    command: sed -i 's/^\$ModLoad imklog/#&/' /etc/rsyslog.conf

  - name: apt-get update
    command: apt-get update

  - name: apt-get clean
    command: apt-get clean

  - name: clean up after debootstrap
    command: rm -rf /debootstrap

- include: install_ssh_keys.yml

