---

- hosts: all

  vars:
    http_port: 8080

  tasks:

  - name: set apache2 name virtual host
    command: sed -i "s/^NameVirtualHost .*/NameVirtualHost *:$http_port/" /etc/apache2/ports.conf

  - name: set apache2 listen port
    command: sed -i "s/^Listen .*/Listen $http_port/" /etc/apache2/ports.conf

  - name: set apache2 default server configuration
    command: sed -i "s/<VirtualHost .:.*>/<VirtualHost *:$http_port>/" /etc/apache2/sites-available/default

- include: restart.yml

