---

- hosts: all

  vars:
    mysql_port: 3306
    shrot_localhost: 127.2.0.1

  tasks:

  - name: set client port
    command: sed -i 's/^\(port.*=\) [0-9][0-9]*$/\1 {{mysql_port}}/' /etc/mysql/my.cnf

  - name: set bind address
    command: sed -i 's/^\(bind-address.*=\) [0-9][0-9.]*$/\1 {{shrot_localhost}}/' /etc/mysql/my.cnf

- include: restart.yml

