---

- hosts: all

  vars:
    mysql_root_password: root

  tasks:

  - name: set password in debconf
    shell: debconf-get-selections | grep mysql-server/root_password | sed 's/$/$mysql_root_password/' | debconf-set-selections

  - name: reconfigure with new password
    shell: dpkg-reconfigure -fnoninteractive $(debconf-get-selections | awk '$2 == "mysql-server/root_password" { print $1 }')

  - name: deactivate init script for mysql
    command: update-rc.d -f mysql remove

  - name: activate init script for mysql
    command: update-rc.d mysql defaults 19 21

  - name: set user in .my.cnf
    ini_file: dest=/root/.my.cnf section=client option=user value=root mode=0600

  - name: set password in .my.cnf
    ini_file: dest=/root/.my.cnf section=client option=password value=$mysql_root_password mode=0600

