---

- include: prepare.yml

- hosts: all
  tasks:

  - name: install init script for mysql
    copy: src=files/etc_init.d_mysql dest=/etc/init.d/mysql.sysv owner=root group=root mode=755

  - name: install mysql
    apt: pkg=mysql-server,python-mysqldb,debconf-utils

- include: set_password.yml

