---

- include: prepare.yml

- include: ../apt/setup.yml

- hosts: all
  tasks:

  - name: install mysql
    apt: pkg=mysql-server,python-mysqldb,debconf-utils

- include: set_port.yml
- include: set_password.yml

- include: ../apt/cleanup.yml

