---

- hosts: all

  vars:
    http_proxy: ''

  tasks:

  - name: install mysql
    apt: pkg=mysql-server,python-mysqldb,debconf-utils
    environment:
      http_proxy: "{{http_proxy}}"

- include: set_port.yml
- include: set_password.yml

