---

- include: prepare.yml

- hosts: all
  vars_files: vars/default.yml
  tasks:

  - name: install init script for mysql
    copy: src=files/etc_init.d_mysql dest=/etc/init.d/mysql.sysv owner=root group=root mode=755

  - name: install mysql
    apt: pkg=mysql-server,python-mysqldb,debconf-utils

  - name: deactivate init script for mysql
    command: update-rc.d -f mysql remove

  - name: activate init script for mysql
    command: update-rc.d mysql defaults 19 21

  - name: set password in debconf
    shell: debconf-get-selections | grep mysql-server/root_password | sed 's/$/$mysql_root_password/' | debconf-set-selections

  - name: reconfigure with new password
    shell: dpkg-reconfigure -fnoninteractive $(debconf-get-selections | awk '$2 == "mysql-server/root_password" { print $1 }')

  - name: create .my.cnf
    template: src=templates/root_my.cnf.j2 dest=/root/.my.cnf mode=0600

