---
  - name: install required packages
    apt: pkg=git-core

  - name: add user git
    user: name=git system=yes shell=/bin/sh comment="Git Version Control" home=/home/git

  - name: add user gitlab
    user: name=gitlab system=yes shell=/bin/sh comment="GitLab" home=/home/gitlab groups=git generate_ssh_key=yes

  - name: fetch gitolite
    git: repo=https://github.com/gitlabhq/gitolite.git dest=/home/git/gitolite version=gl-v320

  - name: fix permissions of gitolite
    command: chown -R git:git /home/git/gitolite

  - name: mkdir ~git/bin
    file: path=/home/git/bin owner=git group=git state=directory

  - name: install gitolite
    command: sudo -u git -H -i sh -c 'gitolite/install -ln /home/git/bin'

  - name: copy the gitlab user's public SSH key
    command: cp /home/gitlab/.ssh/id_rsa.pub /home/git/gitlab.pub

  - name: copy the gitlab user's SSH config
    template: src=templates/home_ssh_config.j2 dest=/home/gitlab/.ssh/config owner=gitlab group=gitlab

  - name: fix permissions of gitlab.pub
    command: chmod 0444 /home/git/gitlab.pub

  - name: use the admin key for the Gitolite setup
    command: sudo -u git -H -i sh -c 'PATH=/home/git/bin:$PATH; gitolite setup -pk /home/git/gitlab.pub'

  - name: fix ownership of Gitolite config dir
    command: chown -R git:git /home/git/.gitolite

  - name: fix permissions of Gitolite config dir
    command: chmod 750 /home/git/.gitolite

  - name: fix ownership of the repositories dir
    command: chown -R git:git /home/git/repositories

  - name: fix permissions of Gitolite config dir
    command: chmod -R ug+rwXs,o-rwx /home/git/repositories

  - name: test if can connect localhost
    shell: sudo -u gitlab -H -i ssh git@localhost -o StrictHostKeyChecking=no -o PasswordAuthentication=no

  - name: test if can clone repository
    command: sudo -u gitlab -H -i git clone git@localhost:gitolite-admin.git /tmp/gitolite-admin

  - name: clean up
    command: rm -rf /tmp/gitolite-admin
