---

  - name: fetch gitlab
    git: repo=https://github.com/gitlabhq/gitlabhq.git dest=/home/gitlab/gitlab version=4-2-stable

  - name: fix permissions of gitlab
    command: chown -R gitlab:gitlab /home/gitlab/gitlab

  - name: create GitLab config file
    template: src=templates/home_gitlab_gitlab_config_gitlab.yml.j2 dest=/home/gitlab/gitlab/config/gitlab.yml owner=gitlab group=gitlab

  - name: create shrot environment config file
    template: src=templates/home_gitlab_gitlab_config_environments_shrot.rb.j2 dest=/home/gitlab/gitlab/config/environments/shrot.rb owner=gitlab group=gitlab

  - name: create mysql config file
    template: src=templates/home_gitlab_gitlab_config_database.yml.j2 dest=/home/gitlab/gitlab/config/database.yml owner=gitlab group=gitlab

  - name: create resque config file
    template: src=templates/home_gitlab_gitlab_config_rescue.yml.j2 dest=/home/gitlab/gitlab/config/rescue.yml owner=gitlab group=gitlab

  - name: create Unicorn config file
    template: src=templates/home_gitlab_gitlab_config_unicorn.rb.j2 dest=/home/gitlab/gitlab/config/unicorn.rb owner=gitlab group=gitlab

  - name: create ~/.my.cnf config file
    template: src=templates/home_gitlab_my_cnf.j2 dest=/home/gitlab/.my.cnf owner=gitlab group=gitlab mode=0600

  - name: make directory for satellites
    file: path=/home/gitlab/gitlab-satellites owner=gitlab group=gitlab state=directory

  - name: bundle install gitlab
    command: script --return -a -f /tmp/gitlab_setup_gitlab.log -c 'sudo -u gitlab -H bundle install --deployment --without development postgres test' chdir=/home/gitlab/gitlab

  - name: set gitlab user name
    command: sudo -u gitlab -H -i git config --global user.name "GitLab"

  - name: set gitlab user email
    command: sudo -u gitlab -H -i git config --global user.email "gitlab@localhost"

  - name: setup gitlab hooks
    command: cp /home/gitlab/gitlab/lib/hooks/post-receive /home/git/.gitolite/hooks/common/post-receive

  - name: fix permissions for gitlab hooks
    file: path=/home/git/.gitolite/hooks/common/post-receive owner=git group=git

  - name: initialise database and activate advanced features
    command: script --return -a -f /tmp/gitlab_setup_gitlab.log -c 'sudo -u gitlab -H sh -c "yes yes | bundle exec rake gitlab:setup RAILS_ENV=shrot"' chdir=/home/gitlab/gitlab

  - name: install init script
    template: src=templates/etc_init.d_gitlab dest=/etc/init.d/gitlab mode=0755

  - name: deactivate init script
    command: update-rc.d -f gitlab remove

  - name: make gitlab start on boot
    command: update-rc.d gitlab defaults 21

  - name: check application status
    command: script --return -a -f /tmp/gitlab_setup_gitlab.log -c 'sudo -u gitlab -H bundle exec rake gitlab:env:info RAILS_ENV=shrot' chdir=/home/gitlab/gitlab

  - name: run a more thorough check
    command: script --return -a -f /tmp/gitlab_setup_gitlab.log -c 'sudo -u gitlab -H bundle exec rake gitlab:check RAILS_ENV=shrot' chdir=/home/gitlab/gitlab

  - name: start gitlab
    service: name=gitlab state=started

