---

  - name: install required packages
    apt: pkg=$item
    with_items:
    - bsdutils
    - build-essential
    - libcurl4-openssl-dev
    - libffi-dev
    - libgdbm-dev
    - libicu-dev
    - libncurses5-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - zlib1g-dev

  - name: download Ruby
    get_url: url=http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p327.tar.gz dest=/tmp/ruby-1.9.3-p327.tar.gz

  - name: unpack Ruby
    command: tar zxf ruby-1.9.3-p327.tar.gz chdir=/tmp

  - name: configure Ruby
    command: script --return -a -f /tmp/gitlab_setup_ruby.log -c './configure' chdir=/tmp/ruby-1.9.3-p327

  - name: make Ruby
    command: script --return -a -f /tmp/gitlab_setup_ruby.log -c 'make' chdir=/tmp/ruby-1.9.3-p327

  - name: install Ruby
    command: script --return -a -f /tmp/gitlab_setup_ruby.log -c 'make install' chdir=/tmp/ruby-1.9.3-p327

