---

  - name: install required packages
    apt: pkg={{item}}
    with_items:
    - bsdutils
    - build-essential
    - libcurl4-openssl-dev
    - libffi-dev
    - libgdbm-dev
    - libicu-dev
    - libncurses5-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - zlib1g-dev
    environment:
      http_proxy: "{{http_proxy}}"

  - name: download Ruby
    get_url: url={{ruby_url}} dest=/tmp/ruby-{{ruby_version}}.tar.gz
    environment:
      http_proxy: "{{http_proxy}}"

  - name: unpack Ruby
    command: tar zxf ruby-{{ruby_version}}.tar.gz chdir=/tmp

  - name: configure Ruby
    command: script --return -a -f /tmp/gitlab_setup_ruby.log -c './configure' chdir=/tmp/ruby-{{ruby_version}}

  - name: make Ruby
    command: script --return -a -f /tmp/gitlab_setup_ruby.log -c 'make' chdir=/tmp/ruby-{{ruby_version}}

  - name: install Ruby
    command: script --return -a -f /tmp/gitlab_setup_ruby.log -c 'make install' chdir=/tmp/ruby-{{ruby_version}}

