---

  - name: create database
    mysql_db: name=gitlabhq_production encoding=utf8 collation=utf8_unicode_ci

  - name: create user
    mysql_user: name=gitlab password='password' priv=gitlabhq_production.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER

