---

- hosts: all

  tasks:

  - name: backup GitLab
    command: script -a -f /tmp/gitlab_backup.log -c 'sudo -u gitlab -H -i bundle exec rake gitlab:app:backup_create RAILS_ENV=production' chdir=/home/gitlab/gitlab

