---

- include: ../nginx/prepare.yml
- include: ../mysql/prepare.yml
- include: ../exim4/prepare.yml

- hosts: all

  vars:
    https_port: 443
    redis_port: 6379

  tasks:

  - name: check if TCP ports are free
    wait_for: port={{item}} state=stopped timeout=1
    with_items:
    - $https_port
    - $redis_port

