---

- hosts: all

  vars:
    https_port: 443

  tasks:
  - include: tasks/prepare.yml

- include: ../ubuntu/add_repo_universe.yml

- hosts: all
  tasks:
  - include: tasks/setup_ruby.yml

- hosts: all
  tasks:
  - include: tasks/setup_ruby_gems.yml
  - include: tasks/setup_gitolite.yml

- include: ../mysql/setup.yml

- hosts: all

  vars:
    db_username: gitlab
    db_password: gitlab

    https_port: 443

    smtp_username: ''
    smtp_password: ''

  tasks:
  - include: tasks/setup_mysql.yml
  - include: tasks/setup_redis.yml
  - include: tasks/setup_gitlab.yml
  - include: tasks/setup_nginx.yml

