---

- include: ../mysql/setup.yml
- include: ../nginx/setup.yml
- include: ../exim4/setup.yml

- hosts: all

  vars:
    ruby_version: 2.0.0-p247
    ruby_url: ftp://ftp.ruby-lang.org/pub/ruby/2.0/ruby-{{ruby_version}}.tar.gz

    gitlab_shell_version: v1.7.0

    gitlab_version: 5-4-stable

    gitlab_admin_email: admin@local.host
    gitlab_admin_password: 5iveL!fe

    db_username: gitlab
    db_password: gitlab

    https_port: 443
    smtp_port: 2520
    redis_port: 6379

    http_proxy: ''

  tasks:
  - include: tasks/setup_ruby.yml
  - include: tasks/setup_ruby_gems.yml
  - include: tasks/setup_gitlab-shell.yml
  - include: tasks/setup_mysql.yml
  - include: tasks/setup_redis.yml
  - include: tasks/setup_gitlab.yml
  - include: tasks/setup_nginx.yml

- include: ../nginx/restart.yml

