---

- include: ../ubuntu/add_repo_universe.yml

- include: ../mysql/setup.yml

- hosts: all

  tasks:
  #- include: tasks/setup_ruby.yml
  #- include: tasks/setup_gitolite.yml
  #- include: tasks/setup_mysql.yml
  #- include: tasks/setup_recipes.yml
  - include: tasks/setup_gitlab.yml
  - include: tasks/setup_nginx.yml
