---

- include: prepare.yml
- include: ../mysql/prepare.yml

- include: ../ubuntu/add_repo_universe.yml
- include: ../debian/use_apt_repository.yml

- include: ../mysql/setup.yml

- hosts: all

  vars:
    db_username: etherpad
    db_password: etherpad

    mysql_port: 3306

    http_port: 8080

  tasks:
  - include: tasks/install_nodejs.yml
  - include: tasks/install_devel.yml
  - include: tasks/install_abiword.yml
  - include: tasks/setup_mysql.yml
  - include: tasks/setup_etherpad-lite.yml

