---

  - name: create database
    mysql_db: name=etherpad encoding=utf8 collation=utf8_unicode_ci

  - name: create user
    mysql_user: name={{db_username}} password='{{db_password}}' priv='etherpad.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,LOCK TABLES'

