#!/bin/sh

arg0="$0"
arg0="${arg0#/etc/rc?.d/[SK][0-9][0-9]}"
job="${arg0%.sh}"

case "$job" in
    upstart-job)
        exec /lib/init/upstart-job.sh "$@"
        ;;
    *)
        if [ -x /etc/init.d/$job.sysv ]; then
            exec /etc/init.d/$job.sysv "$@"
        else
            exec /lib/init/upstart-job.sh "$job" "$@"
        fi
esac
