#!/bin/sh

# Compatibliity wrapper for systems without Upstart daemon
#
# (c) 2013 Piotr Roszatycki <dexter@debian.org>, LGPLv2

arg0="$0"
arg0="${arg0#/etc/rc?.d/[SK][0-9][0-9]}"
arg0="$(basename "$arg0")"
job="${arg0%.sh}"

if [ "$job" = "upstart-job" ]; then
    job="$1"
    shift
fi

if [ -x /etc/init.d/$job.sysv ]; then
    exec /etc/init.d/$job.sysv "$@"
else
    exec /lib/init/upstart-job.sh "$job" "$@"
fi
