#!/bin/sh
initctl.distrib version >/dev/null || exit 0
cmd=`basename "$0"`
case "$cmd" in
    start|stop|reload|restart|status)
        exec initctl.distrib $cmd "$@"
        ;;
    *)
        exec initctl.distrib "$@"
esac
