#!/bin/sh

# Compatibliity wrapper for systems without Upstart daemon
#
# (c) 2013 Piotr Roszatycki <dexter@debian.org>, LGPLv2

die() {
    echo "$@" 1>&2
    exit 1
}

do_cmd() {
    ljob="$1"; shift
    lcmd="$1"; shift

    if [ -x /etc/init.d/$ljob.sysv ]; then
        /etc/init.d/$ljob.sysv $lcmd "$@"
    elif [ -x /etc/init.d/$ljob ] && ! [ -f /etc/init/$ljob.conf ]; then
        /etc/init.d/$ljob $lcmd "$@"
    elif [ -f /etc/init/$ljob.conf ]; then
        initctl.distrib version >/dev/null || exit 0
        case $lcmd in
            status|start|restart|reload)
                initctl.distrib $lcmd "$@" | grep -qs 'start/running'
                ;;
            stop)
                initctl.distrib stop "$@" | grep -qs 'stop/waiting'
                ;;
            *)
                initctl.distrib $lcmd "$@"
        esac
    else
        case $lcmd in
            status|start|restart|reload|stop)
                die "$arg0: Unknown job: $ljob"
                ;;
            *)
                initctl.distrib version >/dev/null || exit 0
                initctl.distrib $lcmd $ljob "$@"
        esac
    fi
}

arg0="$(basename "$0")"

case "$arg0" in
    start|stop|reload|restart|status)
        exec initctl "$arg0" "$@"
        ;;
    *)
        while [ $# -gt 0 ]; do
            case "$1" in
                -*)
                    shift
                    ;;
                *)
                    cmd="$1"
                    shift
                    break
            esac
        done
        while [ $# -gt 0 ]; do
            case "$1" in
                -*)
                    shift
                    ;;
                *)
                    job="$1"
                    shift
                    break
            esac
        done

        case $cmd in
            status)
                if do_cmd $job status "$@" >/dev/null; then
                    echo "$job start/running"
                else
                    echo "$job stop/waiting"
                fi
                ;;
            start)
                if do_cmd $job status "$@" >/dev/null 2>&1; then
                    die "$arg0: Job is already running: $job"
                else
                    if ret=`do_cmd $job $cmd "$@" 2>&1`; then
                        echo "$job start/running"
                    else
                        die "$arg0: Rejected:" $ret
                    fi
                fi
                ;;
            stop)
                if ! do_cmd $job status "$@" >/dev/null 2>&1; then
                    die "$arg0: Unknown instance:"
                else
                    if ret=`do_cmd $job $cmd "$@" 2>&1`; then
                        echo "$job stop/waiting"
                    else
                        die "$arg0: Rejected:" $ret
                    fi
                fi
                ;;
            restart|reload)
                if ! do_cmd $job status "$@" >/dev/null 2>&1; then
                    die "$arg0: Unknown instance:"
                else
                    if ret=`do_cmd $job $cmd "$@" 2>&1`; then
                        echo "$job start/running"
                    else
                        die "$arg0: Rejected:" $ret
                    fi
                fi
                ;;
            *)
                do_cmd $job $cmd "$@"
        esac
esac
