---

  - name: checkout foswiki
    subversion: repo=http://svn.foswiki.org/tags/FoswikiRelease01x01x07/ dest=/home/foswiki

  - name: create local lib configuration
    shell: sed s,/absolute/path/to/your/lib,/home/foswiki/core/lib, /home/foswiki/core/bin/LocalLib.cfg.txt > /home/foswiki/core/bin/LocalLib.cfg

  - name: create local site configuration
    copy: src=files/foswiki_core_lib_LocalSite.cfg dest=/home/foswiki/core/lib/LocalSite.cfg

  - name: create htpasswd file
    command: htpasswd -bc /home/foswiki/core/data/.htpasswd $foswiki_username $foswiki_password

  - name: enable extensions in a checkout area
    command: ./pseudo-install.pl default chdir=/home/foswiki/core

  - name: fix ownership of foswiki directories
    command: chown -R www-data:www-data /home/foswiki

  - name: enable mod_rewrite
    command: a2enmod rewrite

  - name: configure apache2
    copy: src=files/apache2_foswiki.conf dest=/etc/apache2/conf.d/foswiki.conf

  - name: configure apache2 (shorterurl)
    copy: src=files/apache2_foswiki-shorterurl.conf dest=/etc/apache2/conf.d/foswiki-shorterurl.conf

