---

  - name: fetch foswiki from github (Release01x01 branch)
    git: repo=https://github.com/foswiki/$item dest=/home/foswiki/$item version=Release01x01
    with_items:
    - core
    - AutoViewTemplatePlugin
    - BuildContrib
    - CommentPlugin
    - CompareRevisionsAddOn
    - EditTablePlugin
    - EmptyPlugin
    - FamFamFamContrib
    - HistoryPlugin
    - InterwikiPlugin
    - JQueryPlugin
    - JSCalendarContrib
    - MailerContrib
    - PatternSkin
    - PreferencesPlugin
    - RenderListPlugin
    - SlideShowPlugin
    - SmiliesPlugin
    - SpreadSheetPlugin
    - TWikiCompatibilityPlugin
    - TablePlugin
    - TestFixturePlugin
    - TinyMCEPlugin
    - TipsContrib
    - TopicUserMappingContrib
    - TwistyPlugin
    - UnitTestContrib
    - WysiwygPlugin

  - name: fetch foswiki from github (master branch)
    git: repo=https://github.com/foswiki/$item dest=/home/foswiki/$item
    with_items:
    - BreadCrumbsPlugin
    - PatchFoswikiContrib

  - name: create local configuration
    shell: sed s,/absolute/path/to/your/lib,/home/foswiki/core/lib, /home/foswiki/core/bin/LocalLib.cfg.txt > /home/foswiki/core/bin/LocalLib.cfg

  - name: create htpasswd file
    command: htpasswd -bc /home/foswiki/core/data/.htpasswd $foswiki_username $foswiki_password

  - name: enable extensions in a checkout area
    command: ./pseudo-install.pl default chdir=/home/foswiki/core

  - name: enable more extensions
    command: ./pseudo-install.pl $item chdir=/home/foswiki/core
    with_items:
    - BreadCrumbsPlugin

  - name: set breadcrumbs skin as default
    lineinfile: dest=/home/foswiki/core/data/Main/SitePreferences.txt line='   * Set SKIN = breadcrumbs,pattern'

  - name: fix ownership of foswiki directories
    command: chown -R www-data:www-data /home/foswiki

  - name: enable mod_rewrite
    command: a2enmod rewrite

  - name: configure apache2
    copy: src=files/apache2_foswiki.conf dest=/etc/apache2/conf.d/foswiki.conf

  - name: configure apache2 (shorterurl)
    copy: src=files/apache2_foswiki-shorterurl.conf dest=/etc/apache2/conf.d/foswiki-shorterurl.conf

