---

  - name: copy debconf selection
    template: src=templates/foswiki.debconf.j2 dest=/tmp/foswiki.debconf

  - name: run debconf
    command: debconf-set-selections /tmp/foswiki.debconf

  - name: install foswiki
    apt: name=$item
    with_items:
    - foswiki

  - name: enable /etc/foswiki to configuration by web
    command: chown -R www-data:www-data /etc/foswiki

