---

- include: prepare.yml

- hosts: all

  vars:
    tmpdir: /tmp
    smtp_port: 25
    smtp_smarthost: ~
    exim_queue_interval: 5m

  tasks:

  - name: install debconf-utils
    apt: pkg=debconf-utils

  - name: create debian configuration for exim4
    template: src=templates/exim4-config.debconf.j2 dest=$tmpdir/exim4-config.debconf mode=0600

  - name: preconfigure exim4
    command: debconf-set-selections $tmpdir/exim4-config.debconf

  - name: install exim4
    apt: pkg=exim4,debconf-utils

  - name: change queue runner interval
    command: sed -i "s/^\(QUEUEINTERVAL\)=.*/\\1='$exim_queue_interval'/" /etc/default/exim4

  - name: additional settings
    copy: src=files/00_exim4-localmacros dest=/etc/exim4/conf.d/main/00_exim4-localmacros

- include: restart.yml

