---
- hosts: localhost
  tasks:
    #- include: tasks/ubuntu_universe.yml
    #- include: tasks/gitlab_gitolite.yml
    #- include: tasks/mysql.yml
    #- include: tasks/gitlab_mysql.yml
    - include: tasks/gitlab_gitlab.yml
