---
- hosts: localhost
  tasks:

  - name: install mysql
    apt: pkg=mysql-server

  - name: install init.d mysql script
    copy: src=files/etc_init.d_mysql dest=/etc/init.d/mysql owner=root group=root mode=755
