---
- hosts: localhost
  tasks:

  - name: override init.d mysql script
    command: /usr/sbin/dpkg-divert --rename /etc/init.d/mysql

  - name: install init.d mysql script
    copy: src=files/etc_init.d_mysql dest=/etc/init.d/mysql owner=root group=root mode=755

  - name: install mysql
    apt: pkg=mysql-server

